/**
 * Plan 104-05: Summary generator — writes summary.md.
 *
 * THIS IS A PLACEHOLDER. Per plan 104-05 deviation policy and D-13, the
 * real summary content (decisions, action items, open questions) is
 * generated by the user's configured LLM. The plugin sandbox does NOT yet
 * expose a clean mechanism for invoking the gateway's LLM router
 * (ctx.generateReply or similar) — plan 104-09 will add it.
 *
 * Until then, this module writes a deterministic placeholder with quick
 * stats (speaker count, chunk count, duration) that the agent who called
 * meet__join_* can replace on its next turn (reading summary.md, drafting
 * a real summary, overwriting the file via a follow-up tool call).
 *
 * Doing it this way preserves the plan's cost-sensitivity rule — we do
 * NOT hard-code a specific provider/model from inside the plugin.
 */

import { writeFileSync } from "node:fs";
import { join } from "node:path";

/**
 * @param {string} archiveDir
 * @param {object} opts
 * @param {string} [opts.title]
 * @param {number} opts.startedAt  epoch ms
 * @param {number} opts.endedAt    epoch ms
 * @param {object[]} opts.groups   output of archive-writer.groupBySpeaker
 * @param {object[]} opts.chunks   output of archive-writer.readChunks
 * @returns {{summaryMdPath: string}}
 */
export function writeSummaryMd(archiveDir, { title, startedAt, endedAt, groups, chunks }) {
	const speakers = Array.from(new Set(groups.map((g) => g.name))).filter(
		(n) => n && n !== "Unknown speaker",
	);
	const durationMs = Math.max(0, (endedAt ?? 0) - (startedAt ?? 0));
	const mm = Math.floor(durationMs / 60_000);
	const ss = Math.floor((durationMs % 60_000) / 1000);

	const md = [
		`# Meeting Summary — ${title || "(untitled)"}`,
		"",
		"**Status:** Auto-summary placeholder. The agent who initiated this meeting will append a detailed summary here when it next responds. LLM wiring is scheduled for plan 104-09.",
		"",
		"## Quick Stats",
		`- Speakers: ${speakers.length} (${speakers.join(", ") || "none detected"})`,
		`- Transcript chunks: ${chunks.length}`,
		`- Duration: ${mm}:${String(ss).padStart(2, "0")}`,
		"",
		"## Decisions",
		"*(to be filled by the agent)*",
		"",
		"## Action Items",
		"*(to be filled by the agent)*",
		"",
		"## Open Questions",
		"*(to be filled by the agent)*",
		"",
	].join("\n");

	const summaryMdPath = join(archiveDir, "summary.md");
	writeFileSync(summaryMdPath, md);
	return { summaryMdPath };
}
